###
GET http://localhost:3005/users


###
POST http://localhost:3005/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "John",
    "email": "John@gmail.com",
    "password": "John"
}




###
PATCH  http://localhost:3005/users/656bbc43c6d318d50b6b8dd0
Content-Type: application/json

{
    "firstName": "John aaassssa"
}


###
DELETE  http://localhost:3005/users/656bbc43c6d318d50b6b8dd0
Content-Type: application/json
